// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBar.Infrastructure;

#nullable disable

namespace SmartBar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526170043_AddInboxMessages")]
    partial class AddInboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBar.Domain.Entities.Cocktail", b =>
                {
                    b.Property<Guid>("CocktailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecipeSteps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CocktailId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cocktails");

                    b.HasData(
                        new
                        {
                            CocktailId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Description = "Classic cocktail made with rye or bourbon, sweet vermouth, and bitters.",
                            Name = "Manhattan",
                            RecipeSteps = ""
                        });
                });

            modelBuilder.Entity("SmartBar.Domain.Entities.CocktailIngredient", b =>
                {
                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CocktailId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CocktailIngredients");

                    b.HasData(
                        new
                        {
                            CocktailId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            IngredientId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Amount = 60m,
                            Unit = "ml"
                        },
                        new
                        {
                            CocktailId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            IngredientId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Amount = 30m,
                            Unit = "ml"
                        },
                        new
                        {
                            CocktailId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            IngredientId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Amount = 2m,
                            Unit = "dashes"
                        });
                });

            modelBuilder.Entity("SmartBar.Domain.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages");
                });

            modelBuilder.Entity("SmartBar.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IngredientId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Category = "Whiskey",
                            Name = "Bourbon"
                        },
                        new
                        {
                            IngredientId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Category = "Vermouth",
                            Name = "Sweet Vermouth"
                        },
                        new
                        {
                            IngredientId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Category = "Bitters",
                            Name = "Angostura Bitters"
                        });
                });

            modelBuilder.Entity("SmartBar.Domain.Entities.CocktailIngredient", b =>
                {
                    b.HasOne("SmartBar.Domain.Entities.Cocktail", "Cocktail")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBar.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SmartBar.Domain.Entities.Cocktail", b =>
                {
                    b.Navigation("CocktailIngredients");
                });

            modelBuilder.Entity("SmartBar.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("CocktailIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
